### ISSUE TITLE
kitchen test Missing value for required option(s): ''client_name''

### ISSUE THREAD

**Issue by runningman84** [flexiant/kubernetes-install#9]
Is this a known error?

```
-----> Starting Kitchen (v1.8.0)
-----> Creating <cluster-master>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Importing base box 'ubuntu/wily64'...
==> default: Matching MAC address for NAT networking...                                                                        
       ==> default: Checking if box 'ubuntu/wily64' is up to date...
       ==> default: Setting the name of the VM: kitchen-kubernetes-install-cluster-master_default_1466193966385_63533
       ==> default: Clearing any previously set forwarded ports...
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
           default: Adapter 2: hostonly
       ==> default: Forwarding ports...
           default: 22 (guest) => 2222 (host) (adapter 1)
       ==> default: Booting VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...
           default: SSH address: 127.0.0.1:2222
           default: SSH username: vagrant
           default: SSH auth method: private key
           default: Warning: Remote connection disconnect. Retrying...
           default: Warning: Remote connection disconnect. Retrying...
           default: Warning: Remote connection disconnect. Retrying...
           default: 
           default: Vagrant insecure key detected. Vagrant will automatically replace
           default: this with a newly generated keypair for better security.
           default: 
           default: Inserting generated public key within guest...
           default: Removing insecure key from the guest if it's present...
           default: Key inserted! Disconnecting and reconnecting using new SSH key...
       ==> default: Machine booted and ready!
       ==> default: Checking for guest additions in VM...
       ==> default: Setting hostname...
       ==> default: Configuring and enabling network interfaces...
       ==> default: Machine not provisioned because `--no-provision` is specified.
       [SSH] Established
       Vagrant instance <cluster-master> created.
       Finished creating <cluster-master> (0m58.18s).
-----> Converging <cluster-master>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.3.3...
E, [2016-06-17T22:06:42.147163 #8381] ERROR -- : Actor crashed!
ArgumentError: Missing value for required option(s): ''client_name''
        /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.5.1/lib/ridley/client.rb:57:in `validate_options'
        /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.5.1/lib/ridley/client.rb:124:in `initialize'
        /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
        /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
        /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
        /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
        /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
        /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
        /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
        /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [Missing value for required option(s): ''client_name'']
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by willejs** [comment]
@runningman84 have a look at my pull request and try out that branch. Ive been waiting for a code review and merge for ages, and its not happening, so im contemplating hard forking this, and re-writing it.

**Comment by nilskuehme** [comment]
Is there any solution for this issue?
